name: trade_to_ohlc
language: python
variables:
  - name: KAFKA_INPUT_TOPIC
    inputType: InputTopic
    description: ''
    defaultValue: trade
    required: true
  - name: KAFKA_OUTPUT_TOPIC
    inputType: OutputTopic
    description: kafka topic where we push ohlc data
    defaultValue: ohlc
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: the consumer group we use to read data from kafka topic
    defaultValue: trade_to_ohlc_consumer_group
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
