name: trade_to_ohlc
language: python
variables:
  - name: KAFKA_INPUT_TOPIC
    inputType: InputTopic
    description: ''
    defaultValue: trade
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
