name: kafka_to_feature_store
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: InputTopic
    description: ''
    defaultValue: ohlc
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: ''
    defaultValue: ohlc_consumer_group
    required: true
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    description: ''
    defaultValue: ohlc_feature_group
    required: true
dockerfile: Dockerfile
runEntryPoint: main.py
defaultFile: main.py
