name: kafka_to_feature_store
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: InputTopic
    description: ''
    defaultValue: ohlc
    required: true
dockerfile: Dockerfile
runEntryPoint: main.py
defaultFile: main.py
