run:
	source setup_credentials.sh && \
	source setup_config.sh && \
	poetry run streamlit run src/frontend.py

backend:
	source setup_credentials.sh && \
	source setup_config.sh && \
	poetry run python src/backend.py